#!/bin/bash

tmp_file_name=".firetower"

trap "rm -f $tmp_file_name ; exit 0" SIGTERM SIGINT EXIT

function run_child_command() {
  local command="$(get_command "$@")"
  cd "$(get_directory "$@")"
  abort_if_existing_tmp_file "$@"
  while true
  do
    { $command &
      child=$!
      echo "$$ $child" > $tmp_file_name
      echo "Started: $1"
      echo "pid, child-pid"
      cat $tmp_file_name
    } | sed
    echo
  done
}

function abort_if_existing_tmp_file() {
  test -f $tmp_file_name && {
    echo "'.firetower' file already exists in $(pwd)"
    echo "is there already a process using this directory?"
    echo "aborting.."
    exit 1
  }
}

function restart_command() {
  cd "$(get_directory "$@")"
  test -f $tmp_file_name || {
    return 1
  }
  # double tap - some programs request a "ctr-c again to exit"
  child_id="$(cat $tmp_file_name | cut -d ' ' -f 2)"
  kill -15 $child_id
  kill -2 $child_id
}

function stop_firetower() {
  cd "$(get_directory "$@")"
  test -f $tmp_file_name || {
    return 1
  }
  kill $(cat $tmp_file_name)
  rm -f "$tmp_file_name"
}

function usage() {
  echo "usage: $0 [-h help] | [-c command | -r restart_command | -s stop_firetower ] [--directory=directory]"
  exit 0
}

function help() {
  usage
}

function get_flag() {
  if [[ $1 == '-h' ]] ; then
    echo 'help'
  elif [[ $1 == '-c' ]] ; then
    echo 'run_child_command'
  elif [[ $1 == '-r' ]] ; then
    echo 'restart_command'
  elif [[ $1 == '-s' ]] ; then
    echo 'stop_firetower'
  elif [[ ${1:0:1} == '-' ]] || [ "$#" == "0" ] ; then
    # if any other flags are passed, display usage
    echo 'usage'
  else
    echo 'run_child_command'
  fi
}

function get_directory() {
  for var in "$@"
  do
    if [[ $var == --directory=* ]] ; then
      echo "$var" | cut -d '=' -f 2
      return
    fi
  done
  echo "./"
}

function get_command() {
  local flag_passed=""
  local first_arg=$1
  if [[ $first_arg == "-c" ]] ; then
    echo "$2"
  else
    echo "$1"
  fi
}

function debug() {
  echo 'DEBUG'
  echo fla - $(get_flag "$@")
  echo dir - $(get_directory "$@")
  echo com - $(get_command "$@")
  exit 0
}
# debug "$@"

function main() {
  $(get_flag "$@") "$@"
}
main "$@"
